# Лабораторная работа 1. Язык Python, основные библиотеки для анализа данных.

ФИО: Шолохова Татьяна Николаевна

Группа: 317

In [2]:
import numpy as np
import pandas as pd

## Часть 1: Python

#### 1. Напишите код, который сформирует список всех натуральных чисел, не превосходящих 100, которые делятся на 7 и не делятся на 5. Нельзя использовать циклы — выполните это задание с помощью list comprehension.

In [2]:
x = [n for n in range(1, 100) if (n % 5 != 0) and (n % 7 == 0)]
x

[7, 14, 21, 28, 42, 49, 56, 63, 77, 84, 91, 98]

#### 2. Напишите функцию `sort_tokens(s)`, которая принимает на вход строку, разделяет ее на токены по запятым, сортирует токены с помощью функции `sorted()` и снова соединяет их в одну строку через запятые. Например, для строки `u"ночь,фонарь,улица"` функция должна выдать `u"ночь,улица,фонарь"`. Придумайте несколько входных строк и протестируйте функцию на них.

Обратите внимание, что склеить строки можно с помощью конструкции `'x'.join(...)`. Например:

In [3]:
'! '.join(['i', 'am', 'very', 'excited', ':-)'])

'i! am! very! excited! :-)'

In [4]:
def sort_tokens(s):
    s = s.split(',')
    s = sorted(s)
    return ','.join(s)
print(sort_tokens(u"ночь,фонарь,улица"))


ночь,улица,фонарь


In [5]:
print(sort_tokens("a,b,a,c,a,b,a"))

a,a,a,a,b,b,c


In [6]:
print(sort_tokens("abba,abacaba,abracadabra,ab"))

ab,abacaba,abba,abracadabra


#### 3. Напишите функцию `remove_duplicates(a)`, которая принимает на вход список и возвращает его же, но без дубликатов и в отсортированном виде. Например, для списка `[u"ночь", u"улица", u"фонарь", u"аптека", u"аптека", u"улица", u"фонарь"]` результат должен быть `[u"аптека", u"ночь", u"улица", u"фонарь", ]`.

Подсказка: обратите внимание на структуру `set`!

In [7]:
def remove_duplicates(a):
    return sorted(list(set(a)))
s = remove_duplicates([u"ночь", u"улица", u"фонарь", u"аптека", u"аптека", u"улица", u"фонарь"])
print(','.join(s))

аптека,ночь,улица,фонарь


#### 4. Напишите функцию `word_counts(texts)`, которая принимает на вход список строк, и печатает пары (слово, число вхождений). Считайте, что слова в текстах могут быть разделены только пробелами. Например, для входа `[u'ночь улица фонарь аптека', u'аптека улица фонарь']` должно быть напечатано
>аптека 2

>улица 2

>фонарь 2

>ночь 1

Подсказки:

Чтобы разбить каждый из текстов на слова, воспользуйтесь функцией `map`, которая применяет заданную функцию к каждому элементу списка. Например, если бы нужно было каждый из текстов привести к нижнему регистру, то команда выглядела бы так:

In [8]:
map(lambda x: x.lower(), ["abCDefg", "HIjkL"])

['abcdefg', 'hijkl']

После первого шага вы получите список, состоящий из списков слов. Чтобы объединить их в один список слов, воспользуйтесь функцией `reduce`. Например, просуммировать числа из списка с ее помощью можно так:



In [9]:
reduce(lambda x, y: x + y, [1, 2, 3, 4, 5])

15

Для подсчета количества вхождений слов воспользуйтесь структурой `defaultdict` из модуля `collections`. В отличие от обычного `dict`, она не генерирует ошибку при обращении к несуществущему ключу, а создает новую запись, инициализируемую нулевым значением. Например:

In [14]:
from collections import defaultdict
d = defaultdict(int)
print d
d['abc'] += 1
print d
d['xxx']
print d

defaultdict(<type 'int'>, {})
defaultdict(<type 'int'>, {'abc': 1})
defaultdict(<type 'int'>, {'xxx': 0, 'abc': 1})


In [15]:
def word_count(texts):
    texts = list(map(lambda x: x.split(u' '), texts))
    texts = reduce(lambda x, y: x + y, texts)
    from collections import defaultdict
    d = defaultdict(int)
    for x in texts:
        d[x] += 1
    for x in d:
        print x, ' ', d[x]
    

In [16]:
word_count([u'ночь улица фонарь аптека', u'аптека улица фонарь'])

аптека   2
улица   2
фонарь   2
ночь   1


#### 5. (бонусное задание) Скачайте английский перевод "Преступления и наказания". Найдите 20 самых популярных слов и 20 слов, которые встречаются только один раз.

Приведите текст к нижнему регистру. Разделите текст на слова, считая разделителями все, кроме букв. Обратите внимание на функцию `split` из модуля `re`.

Не забудьте удалить пустые слова:
```
words = filter(lambda x: len(x) > 0, words)
```

In [29]:
from urllib import urlopen
url = "http://www.gutenberg.org/files/2554/2554.txt"
response = urlopen(url)
raw_text = response.read().decode('utf8')

In [30]:
raw_text[1000:1100]

u'r five\r\nchildren in only two rooms. The father and mother spent their evenings\r\nin reading aloud to '

In [31]:
raw_text = raw_text.lower()
import re
words = re.split('[^a-z]', raw_text)
words = filter(lambda x: len(x) > 0, words)

In [36]:
d = defaultdict(int)
for w in words:
    d[w] += 1

In [37]:
d = d.items()
d.sort(key = lambda x: x[1], reverse = True)
print d[:20]
print d[-1:-21:-1]

[(u'the', 8003), (u'and', 7042), (u'to', 5497), (u'he', 4900), (u'a', 4668), (u'i', 4405), (u'you', 4118), (u'of', 3928), (u'it', 3463), (u'that', 3308), (u'in', 3254), (u'was', 2827), (u'his', 2116), (u'at', 2082), (u'her', 1829), (u'but', 1801), (u'not', 1775), (u's', 1765), (u'with', 1757), (u'she', 1695)]
[(u'bereaved', 1), (u'sash', 1), (u'upwards', 1), (u'june', 1), (u'transfigured', 1), (u'bombarding', 1), (u'gnawing', 1), (u'unfolding', 1), (u'rickety', 1), (u'venetian', 1), (u'rigamarole', 1), (u'tactics', 1), (u'deuce', 1), (u'funds', 1), (u'uncontrollable', 1), (u'faithfully', 1), (u'noxious', 1), (u'sabre', 1), (u'fawning', 1), (u'lawful', 1)]


## Часть 2: NumPy и SciPy

#### 1. Повторите 1000 раз следующий эксперимент: сгенерируйте две матрицы размера $10 \times 10$ из стандартного нормального распределения, перемножьте их (как матрицы) и найдите максимальный элемент. Какое среднее значение по экспериментам у максимальных элементов? 95-процентная квантиль?

Для вычисления квантили воспользуйтесь функцией `np.percentile`

In [41]:
mx = np.array([])
for i in range(0, 1000):
    A = np.random.normal(size = (10, 10))
    B = np.random.normal(size = (10, 10))
    C = np.dot(A, B)
    mx = np.append(mx, [np.max(C)])
print mx.mean()
print np.percentile(mx, 95)

8.42627361935
12.0155044132


#### 2. Сгенерируйте 1000 чисел из распределения Пуассона с параметром $\lambda = 5$. Сформируйте массив, в котором в i-м элементе будет записано количество сгенерированных чисел, равных i.

Обратите внимание на функцию `np.bincount`

In [44]:
a = np.random.poisson(5, 10)
k = np.bincount(a)
print a
print k

[1 8 4 2 3 4 7 8 7 1]
[0 2 1 1 2 0 0 2 2]


#### 3. Реализуйте функцию, которая принимает на вход numpy-массив целых чисел `a`, и генерирует массив, в котором число `i` встречается `a[i]` раз. Протестируйте на результате из прошлого задания.

Обратите внимание на функцию `np.repeat`

In [47]:
def gen(a):
    return np.repeat(np.arange(len(a)), a)
np.all(gen(k) == sorted(a))

True

#### 4. Напишите функцию `scale(X)`, которая принимает на вход матрицу и масштабирует каждый ее столбец (вычитает среднее и делит на стандартное отклонение). Убедитесь, что в функции не будет происходить деления на ноль. Протестируйте на каких-нибудь данных.

In [18]:
def scale(X):
    m = np.mean(X, axis = 0)
    d = np.std(X, axis = 0)
    d[d == 0] = 1
    return (X - m) / d
a = np.ones((2, 3))
print scale(a)
b = np.arange(15).reshape(5, 3)
print scale(b)


[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


#### 5. Сгенерируйте матрицу с элементами из нормального распределения $\mathcal{N}(10, 1)$. Найдите ее:
- определитель
- след
- наименьший и наибольший элементы
- спектральную норму
- норму Фробениуса
- собственные числа
- обратную матрицу

In [16]:
from scipy import linalg
a = np.random.normal(10, 1, size = (4, 4))
print a
print linalg.det(a)
print np.trace(a)
print np.min(a), np.max(a) 
print np.sqrt(np.max(linalg.eigvals(np.dot(a.T, a)))) 
print linalg.norm(a, ord = 'fro')
print linalg.eigvals(a)
print linalg.inv(a)

[[  9.7526941    8.66159011   9.50691641  10.31450384]
 [  8.92292927   9.35108526  10.48855503  10.98059474]
 [ 12.40640558   9.0369089   10.97932884   9.39471484]
 [  8.02977136  10.06099148  12.78210067  10.18809759]]
-0.047345531735
40.271205787
8.02977136141 12.7821006707
(40.3125280195+0j)
40.5194336404
[  4.02724231e+01+0.j          -4.64670577e-04+2.02067119j
  -4.64670577e-04-2.02067119j  -2.87925358e-04+0.j        ]
[[  -89.08526904    87.03875486    24.43801283   -26.15356833]
 [ 3492.18204582 -3413.9080261   -950.0391847   1020.01011936]
 [-1592.5628416   1556.55880704   433.26919155  -464.84501885]
 [-1380.35396593  1349.84051553   375.34132677  -403.37365111]]


## Часть 3: Pandas

#### Ответьте на вопросы о данных по авиарейсам в США за январь-апрель 2008 года.

Данные: http://stat-computing.org/dataexpo/2009/2008.csv.bz2
(обратите внимание, что распаковывать этот файл не обязательно — функция `pandas.read_csv` умеет читать из архивов автоматически)

Описание: http://stat-computing.org/dataexpo/2009/the-data.html

1. Какая из причин отмены рейса (`CancellationCode`) была самой частой? (расшифровки кодов можно найти в описании данных) 

#####B(weather)
2. Найдите среднее, минимальное и максимальное расстояние, пройденное самолетом.

#####среднее: 726.387029, минимальное: 11, максимальное: 4962
3. Не выглядит ли подозрительным минимальное пройденное расстояние? В какие дни и на каких рейсах оно было? Какое расстояние было пройдено этими же рейсами в другие дни?

#####дата: 15.05.2008, рейс: OH4988, 834 мили в другие дни
#####дата: 10.08.2008, рейс: OH5572, 544 мили в другие дни
4. Из какого аэропорта было произведено больше всего вылетов? В каком городе он находится?

#####"William B Hartsfield-Atlanta Intl", Атланта
5. Найдите для каждого аэропорта среднее время полета (`AirTime`) по всем вылетевшим из него рейсам. Какой аэропорт имеет наибольшее значение этого показателя?

#####"Luis Munoz Marin International"
6. Найдите аэропорт, у которого наибольшая доля задержанных (`DepDelay > 0`) рейсов. Исключите при этом из рассмотрения аэропорты, из которых было отправлено меньше 1000 рейсов (используйте функцию `filter` после `groupby`).

#####"Dallas Love "

In [3]:
t = pd.read_csv('2008.csv.bz2')

In [4]:
np.argmax(t.CancellationCode.value_counts())

'B'

In [5]:
t.Distance.describe()

count    7009728.000000
mean         726.387029
std          562.101803
min           11.000000
25%          325.000000
50%          581.000000
75%          954.000000
max         4962.000000
Name: Distance, dtype: float64

In [6]:
t1 = t[t.Distance == 11]
print t1[['Year', 'Month', 'DayofMonth', 'DayOfWeek', 'UniqueCarrier', 'FlightNum', 'Distance']]
t4988 = t[np.logical_and(t.UniqueCarrier == 'OH', t.FlightNum == 4988)]
t5572 = t[np.logical_and(t.UniqueCarrier == 'OH', t.FlightNum == 5572)]

print 4988, '\n', t4988.Distance.value_counts()
print 5572, '\n', t5572.Distance.value_counts()

         Year  Month  DayofMonth  DayOfWeek UniqueCarrier  FlightNum  Distance
2547298  2008      5          15          4            OH       4988        11
4392215  2008      8          10          7            OH       5572        11
4988 
834    130
96       1
11       1
dtype: int64
5572 
544    243
11       1
dtype: int64


In [7]:
np.argmax(t.Origin.value_counts())

'ATL'

In [8]:
np.argmax(t.groupby('Origin').AirTime.mean())

'SJU'

In [9]:
t4 = t.groupby('Origin')

In [10]:
t4 = t4.filter(lambda x: len(x) >= 1000)

In [11]:
t2 = t4[t4.DepDelay > 0].Origin.value_counts() / t4.Origin.value_counts()
print np.argmax(t2)

DAL
